services:
  - type: web
    name: goldsight-reflex-gui
    runtime: python
    region: singapore
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      reflex export --no-zip
    startCommand: reflex run --env prod --backend-only
    envVars:
      - key: ENV
        value: prod
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: NODE_VERSION
        value: 18
    plan: free
