services:
  - type: web
    name: goldsight-reflex-gui
    runtime: python
    region: singapore
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      reflex init
    startCommand: reflex run --env prod --loglevel info
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: NODE_VERSION
        value: 18
    plan: free
